
import math
import os
from tkinter import filedialog, messagebox, ttk
from PIL import Image
from translations import tr

def load_gif(self):
	file = filedialog.askopenfilename(filetypes=[("GIF", "*.gif")])
	if not file:
		return
	self.gif_image = Image.open(file)
	self.gif_frames = []
	self.texture_image = None
	self.texture_canvas.config(image="")
	try:
		while True:
			self.gif_frames.append(self.gif_image.copy())
			self.gif_image.seek(len(self.gif_frames))
	except EOFError:
		pass
	self.frame_count = len(self.gif_frames)
	self.current_frame = 0
	self.playing = False
	self.play_btn.config(text=tr('play', self.lang) or "Play ▶")
	self.maxframes_var.set(self.frame_count)
	value = 0
	self.frame_select_spin.destroy()
	self.frame_select_spin = ttk.Spinbox(self.add_frame_btn.master, from_=0, to=max(0, self.frame_count-1), textvariable=self.frame_select_var, width=5, state="readonly")
	self.frame_select_spin.pack(side="left", padx=2, before=self.add_frame_btn)
	self.frame_select_var.set(value)
	self.update_previews()
	self.status.config(text=f"{tr('frame_count', self.lang)}: {self.frame_count}")

def save_gif(self):
	if not self.gif_frames:
		messagebox.showerror("Fehler", "Kein GIF geladen.")
		return
	file = filedialog.asksaveasfilename(defaultextension=".gif", filetypes=[("GIF", "*.gif")])
	if not file:
		return
	try:
		frames = [self.apply_effects(f.resize((self.width_var.get(), self.height_var.get())), "gif") for f in self.gif_frames]
		duration = self.framerate_var.get()
		frames[0].save(file, save_all=True, append_images=frames[1:], loop=0, duration=duration)
		messagebox.showinfo("Info", "GIF gespeichert.")
	except Exception as e:
		messagebox.showerror("Fehler", str(e))

def save_texture(self):
	if self.texture_image is None:
		messagebox.showerror("Fehler", "Keine Textur vorhanden.")
		return
	name = "texture"
	if self.gif_image and hasattr(self.gif_image, 'filename'):
		name = os.path.splitext(os.path.basename(self.gif_image.filename))[0]
	frame_count = self.frame_count
	tiles_x = math.ceil(math.sqrt(frame_count))
	tiles_y = math.ceil(frame_count / tiles_x)
	speed_val = self.framerate_var.get()
	speed = f"{speed_val};0"
	ext = self.export_format_var.get().lower()
	defext = f".{ext}"
	filetypes = [(ext.upper(), f"*.{ext}") for ext in ["png", "jpg", "bmp"]]
	file = filedialog.asksaveasfilename(defaultextension=defext, initialfile=f"{name};{tiles_x};{tiles_y};{speed}.{ext}", filetypes=filetypes)
	if not file:
		return
	fmt = self.export_format_var.get().upper()
	if fmt == "JPG":
		fmt = "JPEG"
	try:
		img = self.texture_image
		if fmt == "JPEG":
			img = img.convert("RGB")
		img.save(file, format=fmt)
		messagebox.showinfo("Info", "Textur gespeichert.")
	except Exception as e:
		messagebox.showerror("Fehler", str(e))

def export_lsl(self):
	if not self.gif_frames:
		messagebox.showerror("Fehler", "Kein GIF geladen.")
		return
	frame_count = self.frame_count
	tiles_x = math.ceil(math.sqrt(frame_count))
	tiles_y = math.ceil(frame_count / tiles_x)
	name = "texture"
	if self.gif_image and hasattr(self.gif_image, 'filename'):
		name = os.path.splitext(os.path.basename(self.gif_image.filename))[0]
	speed = 10.0
	lsl = generate_lsl_script(self, name, tiles_x, tiles_y, speed)
	file = filedialog.asksaveasfilename(defaultextension=".lsl", initialfile=f"{name}.lsl", filetypes=[("LSL", "*.lsl"), ("Text", "*.txt")])
	if not file:
		return
	try:
		with open(file, "w", encoding="utf-8") as f:
			f.write(lsl)
		messagebox.showinfo("Info", "LSL-Skript exportiert.")
	except Exception as e:
		messagebox.showerror("Fehler", str(e))

def generate_lsl_script(self, name, tiles_x, tiles_y, speed):
	return f'''// LSL Texture Animation Script\n// Generated by OSSL2Gif\n// Texture: {name};{tiles_x};{tiles_y};{speed}\n\ninteger animOn = TRUE;\nlist effects = [LOOP];\ninteger movement = 0;\ninteger face = ALL_SIDES;\ninteger sideX = {tiles_x};\ninteger sideY = {tiles_y};\nfloat start = 0.0;\nfloat length = 0.0;\nfloat speed = {speed};\n\ninitAnim() {{\n    if(animOn) {{\n        integer effectBits;\n        integer i;\n        for(i = 0; i < llGetListLength(effects); i++) {{\n            effectBits = (effectBits | llList2Integer(effects,i));\n        }}\n        integer params = (effectBits|movement);\n        llSetTextureAnim(ANIM_ON|params,face,sideX,sideY,start,length,speed);\n    }}\n    else {{\n        llSetTextureAnim(0,face,sideX,sideY,start,length,speed);\n    }}\n}}\n\nfetch() {{\n     string texture = llGetInventoryName(INVENTORY_TEXTURE,0);\n            llSetTexture(texture,face);\n            list data  = llParseString2List(texture,";",[]);\n            string X = llList2String(data,1);\n            string Y = llList2String(data,2);\n            string Z = llList2String(data,3);\n            sideX = (integer) X;\n            sideY = (integer) Y;\n            speed = (float) Z;\n            if (speed) \n                initAnim();\n}}\n\ndefault\n{{\n    state_entry()\n    {{\n        llSetTextureAnim(FALSE, face, 0, 0, 0.0, 0.0, 1.0);\n        fetch();\n    }}\n    changed(integer what)\n    {{\n        if (what & CHANGED_INVENTORY)\n        {{\n            fetch();\n        }}\n    }}\n}}\n'''
